// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdqvbxwgewgjjlgsypig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkcXZieHdnZXdnampsZ3N5cGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk1MjQ0NTQsImV4cCI6MjA5NTEwMDQ1NH0.9jP5HwrLhWmMs6oM2TdnQP-lwh5Ee72Ko_Wi3rfTlLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});